### ISSUE TITLE
Poimenovanje datotek

### ISSUE THREAD

**Issue by jaanos** [matejaroglic/Racunalniske_igre#1]
Trenutno imata na repozitoriju datoteko `racunalniske_igreNova.db` - to smo naredili zato, da nismo prepisali stare baze, dokler nista prenesli vseh podatkov. Kot vidim, sta sedaj uvozili podatke, tako da ni razloga, da imata na repozitoriju obe datoteki. Datoteki naj bo seveda ime `racunalniske_igre.db`, tako kot imata v programu.

Prav tako opažam, da sta datoteki `funkcije.py` in `funkcije1.py` enaki, tako da eno pobrišita. Ideja git-a je, da se hranijo vse vmesne različice - tako ni potrebe, da delata kopije vaših datotek, pač pa enostavno delata na obstoječih datotekah - git zna namreč tudi združevati spremembe, tako da ni problema, če obe hkrati delata na isti datoteki (če se pa kaj zalomi, pa vas bo prosil, da sami poskrbita za združevanje).

**Comment by ghost** [comment]
V bistvu sva se odločili za drugačno strukturo in bi radi izbrisali vse datoteke iz repozitorija (razen Povezave in README). Večina datotek iz repozitorija je bila namenjena predvsem uvažanju podatkov v bazo, tega pa sedaj ne porebujeva več, saj imava novo bazo z vsemi potrebnimi podatki. Zanima me, kakšen je konceptualno pravilen način brisanja datotek iz repozitorija. Če vse "počistiva" in zamenjava z datotekami, ki so sedaj pomembne (in jih je precej manj), bo namreč lažje delati naprej z GitHubom.

**Comment by jaanos** [comment]
Svetoval bi, da trenutnih datotek ne brišeta (res da so stare različice dosegljive, ampak morda jih bosta vseeno želeli imeti pri roki), pač pa zanje naredita novo mapo (npr. `uvoz`) in jih postavita tja (seveda brez podvajanja). Potem imata lahko vrhnjo mapo za spletni vmesnik (ali pa kako drugače organizirata datoteke).

Kar se samega preurejanja tiče, pa lahko datoteke pri sebi enostavno premikata oziroma brišeta, pa te spremembe vključita v commit (pri premikanju bo potrebno obkljukati brisanje stare in dodajanje nove datoteke - tedaj bo git ugotovil, da se je datoteka samo premaknila, in to ustrezno zabeležil).
