### ISSUE TITLE
Dodajanje igre v bazo

### ISSUE THREAD

**Issue by ghost** [matejaroglic/Racunalniske_igre#2]
Pri dodajanju igre v bazo pride do napake "sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type", najverjetneje pri branju podatkov, ki jih uporabnik vnese. Domnevava, da je napaka v dodaj_igro.tpl ali v rac_igre.py, vendar izvora napake nisva ugotovili.

**Comment by jaanos** [comment]
V `dodaj_igro.tpl` naj imajo značke `<input>` nastavljen atribut `name` namesto `id` (npr. `name="ime_igre"`). Polja v `request.forms` so potem terice, tako da dobita npr. ime igre kot
```python
ime = request.forms.ime_igre[0]
```
Pazita še v `modeli.py` - v funkciji `najdi_podjetje`, se v primeru, ko podjetja ni v bazi, izvede nepravilen SQL stavek - stolpec `ime` mora biti v oklepajih. V funkciji `dodaj_igro_v_bazo` pri vstavljanju v tabelo `igra` podasta še stolpec `datum`, a tega nimata v bazi (vsaj ne v tej, ki je na GitHubu).

**Comment by matejaroglic** [comment]
Če napišemo request.forms.ime_igre[0] program vrne namesto niza prvo črko niza npr: ('F',) namesto 'For Honor', ta črka pa še vedno ostane v terici.

**Comment by jaanos** [comment]
Aha, vidim, kje je problem - na koncu vrstic imate vejice, zaradi česar vam naredi terice. Če izpustite vejice, bo ta del šel čez.

Bo pa treba popraviti funkcijo `najdi_podjetje`, da vedno vrne številko in ne terice. Če je podjetje že v bazi (torej `id` ni `None`), bo treba vrniti prvi element terice `id` (lahko rečeta kar `id = id[0]`). Popravita tudi zadnja dva ukaza `execute` v funkciji `dodaj_igro_v_bazo` - parametra SQL stavka dajta v seznam.

**Comment by ghost** [comment]
hvala za pomoč!
